version: '2'

services:

  redmine:
    image: 'redmine:4.2.9'
    container_name: Redmine_4_2_9
    restart: always
    ports:
      - '80:3000'
    environment:
      REDMINE_DB_MYSQL: mysql
      REDMINE_DB_USERNAME: root
      REDMINE_DB_PASSWORD: example
      # DB에 한글을 사용하기 위한 명령
      REDMINE_DB_ENCODING: utf8
    volumes:
      - './Redmine_Data/Redmine/files:/usr/src/redmine/files'
      - './Redmine_Data/Redmine/public/system:/usr/src/redmine/public/system'
      - './Redmine_Data/Redmine/plugins:/usr/src/redmine/plugins'
    depends_on:
      - mysql

  mysql:
    image: 'mysql:5.7.33'
    container_name: MySQL_5_7_33
    restart: always
    ports:
      - '33306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: redmine
    # DB에 한글을 사용하기 위한 명령
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - './Redmine_Data/Mysql:/var/lib/mysql'
